Homework 12
nkokina/SauceDemo_NatashaKokina_QA19 pull request #4
Opened 2022-07-24 08:07 UTC by nkokina

2022-07-24 21:51 UTC, voropa requested changes

2022-07-24 21:51 UTC, voropa commented on src/main/java/pages/ProductsPage.java
> +        Assert.assertTrue(sortedList.equals(obtainedList), "AZ");
В page классах не должно быть никаких проверок и тестовых данных, Все проверки должны бть в тестах.
Методы в page классах должны толлько возвращать данные со страницы

2022-07-24 21:51 UTC, voropa commented on src/main/java/pages/ProductsPage.java
> +    public void sortZA() {
Думаю, что вмест овсех этих методов можно написать один универсальный, который будет входным аргументом принимать тип сортировки, типа "From A to Z". По сути все ваши методы отличаются только выбором опции в selectByVisibleText

2022-07-24 21:51 UTC, voropa commented on src/main/java/tests/FooterTest.java
> +        driver.navigate().back();
При оспользовании page object pattern, у нас не должно быть никаких driver.методов в тестах, все должно быть скрыто внутри page классов. Переделайте логику метода getPageTransition и поместите туда все действия в навигацией и драйвером. И переименуйте этот метод, как-то он непонятно называется)

2022-07-27 08:52 UTC, voropa requested changes

2022-07-27 08:52 UTC, voropa commented on src/main/java/pages/ProductsPage.java
> +    public void clickAddToCartButton() {
Этот метод у вас нажимет кнопку addtoCart всегда для первого продукта на стринице. А что если нужно добавить 2ой или 3ей продукт в корзину? Метод должен принимать входным аргументом имя товара и добавлять конкретный товар по  имени

2022-07-27 08:52 UTC, voropa commented on src/main/java/tests/FooterTest.java
> +        driver.manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
А зачем вы тут убираете implicityWait у драйвера?

2022-07-27 08:52 UTC, voropa commented on src/main/java/tests/SortTests.java
> +        List<String> expectedListOfProductsName = productsPage.getListOfProductsName();
ExpectedResult не должен получатся с остраницы. Со страницы мы берем actualResult, а wexpected должен быть заготовлен где-то в тестовых данных

2022-07-27 10:12 UTC, nkokina commented on src/main/java/tests/FooterTest.java
> +        driver.manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
я хотела увеличить время ожидания пока страница загрузиться, не дописала цифру...

2022-07-27 11:28 UTC, voropa commented on src/main/java/tests/FooterTest.java
> +        driver.manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
Хах, так implicityWait никак не влияет на время ожидания загрузки страницы. Он применяется только при вызове методов findElement/FindElements, а вы  там ничего не ищете на новой странице, так что он вам никак не  поможет там

Да и зачем что-то ждать: кликнули на сллыку, проверили, что открылась новая вкладка и проверили, что в новой вкладке url == expetcedUrl, вот и все

2022-08-11 13:00 UTC, voropa requested changes

2022-08-11 13:00 UTC, voropa commented on src/main/java/pages/LoginPage.java
> +    @Step("isErrorMessageDisplayed")
Степы имеет смысл добавлять только на те методы, которые выполняют какие-то действия на странице, типа click, sendKeys, а для методов isDisplayed или getValue нет смысла их добавлять

2022-08-11 13:00 UTC, voropa commented on src/main/java/pages/LoginPage.java
> +    @Step("setPassword")
Когда в методе есть водной аргумент, хорошо бы его добавить в описание степа: @Step("setting password = {password}")

2022-08-11 19:25 UTC, voropa requested changes

2022-08-11 19:25 UTC, voropa commented on src/main/java/pages/LoginPage.java
> +    @Step("setting userName = {standard_user}")
В {}нужно писать название переменной, которая у вас является входным аргументом в методе, т.е. userName, тогда в репорте будет реальное значение этой переменной, с которой был вызван метод

2022-08-14 19:12 UTC, voropa approved these changes

2022-08-15 20:15 UTC, merged